### ISSUE TITLE
generateDocs.js is not working

### ISSUE THREAD

**Issue by burib** [arminhammer/cfn-doc-json-stubs#3]
I was trying to run generateDocs.js to update docs.md because it's missing files from the  ```json/resources``` folder and the properties.json file from ```json/properties/properties.json```.

Based on commit history I don't see any signs of how were ```json/resources``` or the ```properties.json``` originally generated.

**Comment by burib** [comment]
for reference: 
 - https://github.com/arminhammer/cfn-doc-json-stubs/blob/master/generateDocs.js#L7
 - https://github.com/arminhammer/cfn-doc-json-stubs/blob/master/generateDocs.js#L25

**Comment by arminhammer** [comment]
Hi @burib, you're right, generateDocs.js is out of date and expects the layout of the json/ folder to be different from what it is now. I initially had the property and resource types as separate folders, but I ended up organizing them by service.

I would be happy to fix this, but I don't think it is worth the effort now that this project has been made obsolete because AWS publishes the CloudFormation spec as JSON now: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html. As far as I can tell my scraper is pretty accurate compared to the spec file, but clearly getting the spec directly from AWS will be preferable and easier to maintain. I recommend using the official spec file.
