### ISSUE TITLE
node generate.js download - command not working

### ISSUE THREAD

**Issue by chetankalore** [arminhammer/cfn-doc-json-stubs#8]
I am getting following error. I am using node - v0.10.46

const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by arminhammer** [comment]
Hey @chetankalore! ```const``` was introduced in ES6 and supported in newer versions of nodejs. I believe node v6 is the minimum version you would need to run the script.

In any case, this project has been made obsolete because AWS publishes the CloudFormation spec as JSON now: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html. I strongly recommend using that file instead of this project.
